### ISSUE TITLE
BUILD FAILING ON UBUNTU

### ISSUE THREAD

**Issue by dlgeraghty** [torrinfail/dwmblocks#24] opened 2020-06-21 13:08 UTC
tried to build using the makefile, it failed in ubuntu (maybe I was missing some libs but I doubt that...)
searching in the internet I came to try : `gcc dwmblocks.c -lX11 -o dwmblocks` which successfully compiled

**Comment by torrinfail** [comment] 2020-06-30 04:06
I would need the error that make spit out to help with that.

**Comment by mendezmariano** [comment] 2020-07-14 03:17
here it comes:
$ make
cc `pkg-config --cflags x11` `pkg-config --libs x11` dwmblocks.c -o dwmblocks
/usr/bin/ld: /tmp/ccg6dlqE.o: in function `setroot':
dwmblocks.c:(.text+0x3b6): undefined reference to `XOpenDisplay'
/usr/bin/ld: dwmblocks.c:(.text+0x428): undefined reference to `XStoreName'
/usr/bin/ld: dwmblocks.c:(.text+0x437): undefined reference to `XCloseDisplay'
collect2: error: ld returned 1 exit status

**Comment by torrinfail** [comment] 2020-07-14 20:03
I have come across this issue on my pinebook pro running debian. I never figured out the root cause myself. The way I got it to work was by using clang (`CC=clang make`) in the most recent commit. Things to check if you prefer using gcc, check the output of  `pkg-config --libs x11` by itself, and make sure that cc is linked to gcc properly with `ls -l $(which cc)`. The makefile works on arch, void, alpine, freebsd, and openbsd. So I think it is just an issue with debian distros.

**Comment by torrinfail** [comment] 2020-08-12 03:25
I merged a change that swapped the order of the cc arguments in the Makefile which should solve this issue.

**Closed by torrinfail** 2020-08-12 03:25 UTC

**Comment by thierrybo** [comment] 2020-12-24 11:32
Hi,

yes but you swap cc arguments order back again in https://github.com/torrinfail/dwmblocks/commit/7e0bc3f5801ba70fcf6d5824a74e29836b2d57b7, so the issue is always there in Debian.

	${CC} dwmblocks.c `pkg-config --cflags x11 --libs x11` -o dwmblocks
just work fine.

**Comment by audrew** [comment] 2022-06-28 18:12
> Hi,
> 
> yes but you swap cc arguments order back again in [7e0bc3f](https://github.com/torrinfail/dwmblocks/commit/7e0bc3f5801ba70fcf6d5824a74e29836b2d57b7), so the issue is always there in Debian.
> 
> ```
> ${CC} dwmblocks.c `pkg-config --cflags x11 --libs x11` -o dwmblocks
> ```
> 
> just work fine.

Thanks, that worked fine
